### PR TITLE
On over-temperature alarm, only set backlight when needed

### PR DESCRIPTION
**Pull request by presslab-us**
With previous code it is not possible to turn off the backlight over RAPI while charging.

Tested using TESTING_TEMPERATURE_OPERATION and flashing backlight worked as expected.

### CODE REVIEW

**Comment by lincomatic** [comment]
Thank you for the pull request. I'm waiting for CraigK to review it, as he is the author of the overtemperature code. In the future, please submit pull requests only to the development branch, as the stable branch is only for promoted code from the development branch.

**Comment by presslab-us** [comment]
I wasn't sure about that because development is some commits behind stable.  Would you like me to rebase this on the development branch?

**Comment by craigk46** [comment]
Sam,
I'm away from home with little ability to review it and test anything until Sunday 10th.  I can look at it then.  Pardon the big delay. 

Best Wishes,
Craig Kirkpatrick 
971-770-8140

On Jan 5, 2016, at 10:18 PM, lincomatic <notifications@github.com> wrote:

Thank you for the pull request. I'm waiting for CraigK to review it, as he is the author of the overtemperature code. In the future, please submit pull requests only to the development branch, as the stable branch is only for promoted code from the development branch.

**Comment by presslab-us** [comment]
@craigk46 did you have a chance to look at this?  Thanks!

**Comment by presslab-us** [comment]
New pull request based on development branch here: https://github.com/lincomatic/open_evse/pull/57

**Pull request closed without merging**
